### ISSUE TITLE
error handling on connection failure

### ISSUE THREAD

**Issue by evanshortiss** [dominicrico/obd-parser-bluetooth-connection#1]
This line https://github.com/dominicrico/obd-parser-bluetooth-connection/blob/master/index.js#L73 needs to call `onConnectionOpened(configureFn, err);` to make sure all possible connect calls get a response.

It's a small bug, but might cause issues with the process not exiting/dying properly.

**Comment by dominicrico** [comment]
Thanks, will add it!

**Comment by dominicrico** [comment]
Fixed with 6d31efee8a6e217ff72e46c331aad31e57e5b94f
